services:
  llm-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-bridge-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # 服务器配置
      - PORT=8080
      - HOST=0.0.0.0
      
      # Redis配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      
      # LLM提供商API密钥 - 从.env文件读取
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_BASE_URL=${GEMINI_BASE_URL:-https://generativelanguage.googleapis.com/v1beta}
      - GEMINI_PROJECT=${GEMINI_PROJECT:-}
      - GEMINI_LOCATION=${GEMINI_LOCATION:-}
      
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL:-https://api.deepseek.com/v1}
      
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - QWEN_BASE_URL=${QWEN_BASE_URL:-https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation}
      
      - MOONSHOT_API_KEY=${MOONSHOT_API_KEY}
      - MOONSHOT_BASE_URL=${MOONSHOT_BASE_URL:-https://api.moonshot.cn/v1}
      
      # 限流配置
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-false}
      - RATE_LIMIT_WINDOW_1M=${RATE_LIMIT_WINDOW_1M:-60}
      - RATE_LIMIT_WINDOW_5M=${RATE_LIMIT_WINDOW_5M:-240}
      - RATE_LIMIT_WINDOW_1H=${RATE_LIMIT_WINDOW_1H:-1000}
      - RATE_LIMIT_CHAT_1M=${RATE_LIMIT_CHAT_1M:-30}
      - RATE_LIMIT_CHAT_5M=${RATE_LIMIT_CHAT_5M:-120}
      - RATE_LIMIT_TEST_1M=${RATE_LIMIT_TEST_1M:-10}
    
    volumes:
      # 可选：挂载日志目录
      - ./logs:/app/logs
    
    networks:
      - llm-bridge-network
    
    depends_on:
      - redis
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    labels:
      - "app=llm-bridge"
      - "service=gateway"
      - "version=1.0.0"

  # Redis服务 - 用于统计、缓存、token计量等
  redis:
    image: redis:7-alpine
    container_name: llm-bridge-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    command: >
      sh -c "
        if [ -n \"$REDIS_PASSWORD\" ]; then
          redis-server --requirepass \"$REDIS_PASSWORD\"
        else
          redis-server
        fi
      "
    volumes:
      - redis_data:/data
    networks:
      - llm-bridge-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  llm-bridge-network:
    driver: bridge
    name: llm-bridge-network

volumes:
  logs:
    driver: local
  redis_data:
    driver: local